package de.docs_as_co.intellij.plugin.zenuml.settings

import com.intellij.openapi.Disposable
import com.intellij.openapi.ui.ComboBox
import com.intellij.ui.components.JBCheckBox
import com.intellij.ui.components.JBLabel
import com.intellij.ui.components.JBTextField
import com.intellij.util.ui.FormBuilder
import com.intellij.util.ui.JBUI
import com.intellij.util.ui.UI
import javax.swing.JComponent
import javax.swing.JPanel
import javax.swing.JSpinner
import javax.swing.SpinnerNumberModel

/**
 * Form for ZenUML settings
 */
class ZenUmlSettingsForm : Disposable {
    private val autoGenerateDiagramCheckBox = JBCheckBox("Auto-generate diagram")
    private val includePrivateMethodsCheckBox = JBCheckBox("Include private methods")
    private val maxCallDepthSpinner = JSpinner(SpinnerNumberModel(5, 1, 20, 1))
    
    private val mainPanel: JPanel = FormBuilder.createFormBuilder()
        .addComponent(JBLabel("ZenUML Settings"), 1)
        .addVerticalGap(10)
        .addComponent(autoGenerateDiagramCheckBox)
        .addComponent(includePrivateMethodsCheckBox)
        .addLabeledComponent("Maximum call depth:", maxCallDepthSpinner)
        .addComponentFillVertically(JPanel(), 0)
        .panel
        .apply {
            border = JBUI.Borders.empty(10)
        }

    val component: JComponent
        get() = mainPanel

    fun isModified(settings: ZenUmlApplicationSettings): Boolean {
        return autoGenerateDiagramCheckBox.isSelected != settings.autoGenerateDiagram ||
                includePrivateMethodsCheckBox.isSelected != settings.includePrivateMethods ||
                maxCallDepthSpinner.value as Int != settings.maxCallDepth
    }

    fun apply(settings: ZenUmlApplicationSettings) {
        settings.autoGenerateDiagram = autoGenerateDiagramCheckBox.isSelected
        settings.includePrivateMethods = includePrivateMethodsCheckBox.isSelected
        settings.maxCallDepth = maxCallDepthSpinner.value as Int
    }

    fun reset(settings: ZenUmlApplicationSettings) {
        autoGenerateDiagramCheckBox.isSelected = settings.autoGenerateDiagram
        includePrivateMethodsCheckBox.isSelected = settings.includePrivateMethods
        maxCallDepthSpinner.value = settings.maxCallDepth
    }

    override fun dispose() {
        // No resources to dispose
    }
} 