package de.docs_as_co.intellij.plugin.zenuml.settings

import com.intellij.openapi.components.PersistentStateComponent
import com.intellij.openapi.components.State
import com.intellij.openapi.components.Storage
import com.intellij.util.xmlb.XmlSerializerUtil

/**
 * Application-level settings for ZenUML
 */
@State(
    name = "ZenUmlApplicationSettings",
    storages = [Storage("zenuml.xml")]
)
class ZenUmlApplicationSettings : PersistentStateComponent<ZenUmlApplicationSettings> {
    var autoGenerateDiagram = true
    var includePrivateMethods = false
    var maxCallDepth = 5

    override fun getState(): ZenUmlApplicationSettings = this

    override fun loadState(state: ZenUmlApplicationSettings) {
        XmlSerializerUtil.copyBean(state, this)
    }

    companion object {
        val DEFAULT = ZenUmlApplicationSettings()
    }
} 